### Obtener todas las vacaciones computadas
GET http://localhost:1234/vacations



###  Insertar vacaciones 
POST http://localhost:1234/vacations 
Content-Type: application/json

{
  "fechaInicio": "2022-01-12T00:00:00.000Z",
  "fechaFin": "2022-01-28T00:00:00.000Z",
  "comentarios": "aosdkastema",
  "legajo_id": 2,
  "administrador_id": 2
}

### Actualizar estado vacaciones

PATCH http://localhost:1234/vacations/5
Content-Type: application/json

{
  "estado" : "Aceptado"
}